name: getx_flutter_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5 #状态管理库
  dio: ^4.0.6 #网络请求库
  flutter_easyrefresh: ^2.2.2 #刷新组件
  cached_network_image: ^3.2.1 #图片缓存
  date_format: ^2.0.6 #日期处理
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

